apiVersion: v1
kind: PersistentVolume
metadata:
  name: hlf-artifacts-pv
spec:
  storageClassName: manual 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/hlf-artifacts"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hlf-artifacts-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi