apiVersion: v1
kind: Service
metadata:
  name: org0-peer0
spec:
  type: NodePort
  selector:
    app: org0-peer0
  ports:
  - name: app
    protocol: TCP
    port: 7051
    targetPort: 7051
    nodePort: 30200
  - name: operations
    protocol: TCP
    port: 9443
    targetPort: 9443
    nodePort: 30201

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: org0-peer0
  labels:
    app: org0-peer0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org0-peer0
  template:
    metadata:
      labels:
        app: org0-peer0
    spec:

      volumes:
      - name: hlf-artifacts
        persistentVolumeClaim:
          claimName: hlf-artifacts-pvc
      - name: core-yaml
        configMap:
          name: core-yaml
          items:
          - key: "core.yaml"
            path: "core.yaml"
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock

      initContainers:
      - name: alpine
        image: alpine:3
        command: ['sh', '-c', 'sleep 30']

      containers:
      - name: couchdb
        image: couchdb:3.1.1
        env:
        - name: COUCHDB_USER
          value: user
        - name: COUCHDB_PASSWORD
          value: pass
        ports:
        - name: db
          containerPort: 5984

      - name: peer
        image: hyperledger/fabric-peer:2.3.0
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        command: ["peer"]
        args: ["node", "start"]
        ports:
        - name: app
          containerPort: 7051
        - name: operations
          containerPort: 9443
        env:
        - name: TZ
          value: "America/Bogota"
        - name: CORE_PEER_ID
          value: "org0-peer0"
        - name: CORE_PEER_LOCALMSPID
          value: "Org0"
        - name: CORE_NETWORKID
          value: "dev"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "org0-peer0:7051"
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: "org0-peer0:7051"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: "user"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: "pass"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: CORE_PEER_TLS_CLIENTROOTCAS_FILES
          value: "msp/tlscacerts/tlsca.Org0-cert.pem"

        volumeMounts:
        - name: hlf-artifacts
          mountPath: "/etc/hyperledger/fabric"
          subPath: "certs/peerOrganizations/Org0/peers/org0-peer0"
        - name: core-yaml
          mountPath: "/etc/hyperledger/fabric/core.yaml"
          subPath: "core.yaml"
        - name: docker-socket
          mountPath: /var/run/docker.sock